#!/usr/bin/env bash
# a Bash script which pings an IP address passed as an argument:
#+ It accepts a string as an argument
#+ It displays 'Usage: 5-is_the_host_on_the_network {IP_ADDRESS}' if no argument passed
#+ Pings the IP 5 times

if [ "$#" -eq 0 ]; then
   echo 'Usage: 5-is_the_host_on_the_network {IP_ADDRESS}'
else
	ping -c 5 "$1"
fi
